--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

local v0=loadstring(game:HttpGet("https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wizard"))();local v1=v0:NewWindow("Google Play’s Diamond");local v2=v1:NewSection("Main");local v3=false;v2:CreateToggle("Inf Token",function(v9) local v10=43 -(35 + 8) ;while true do if (v10==(952 -(802 + 150))) then v3=v9;if v3 then task.spawn(function() while v3 do local v15=0 -0 ;local v16;while true do if (v15==(1267 -(97 + 1169))) then game:GetService("ReplicatedStorage"):WaitForChild("ObbyTokens_CollectItemServerEvent"):FireServer(unpack(v16));break;end if (v15==(1065 -(68 + 997))) then task.wait();v16={{Id="ExpPickup_5",Position=Vector3.new( -(82.550537109375 -63),260.3798828125 -(32 + 85) ,10.000038146972656 + 7 ),RequiredLevel=0 + 0 ,SettingsKey="ExpPickup"},{ItemVisual=game:GetService("ReplicatedStorage"):WaitForChild("PickupVisuals"):WaitForChild("Token2"),AttractTweenTime=1187.35 -(1069 + 118) ,GetItemMultiplier=function() end,OnItemPickedUp=function() end,GetCollectDistance=function() end}};v15=2 -1 ;end end end end);end break;end end end);local v4=game:GetService("Players");local v5=v4.LocalPlayer;local v6=v5.Character or v5.CharacterAdded:Wait() ;local v7=false;v2:CreateToggle("Auto Collect Token",function(v11) local v12=957 -(892 + 65) ;while true do if (v12==(0 + 0)) then v7=v11;if v7 then task.spawn(function() while v7 do local v17=0 -0 ;local v18;while true do if (v17==(1 -0)) then task.wait(0.4 -0 );break;end if (v17==(791 -(368 + 423))) then v18=workspace:FindFirstChild("GoogleTokens");if v18 then for v19,v20 in ipairs(v18:GetChildren()) do if  not v7 then break;end local v21=v20:FindFirstChild("GoogleToken") or v20.PrimaryPart ;if (v21 and v6 and v6:FindFirstChild("HumanoidRootPart")) then local v22=350 -(87 + 263) ;while true do if (v22==(18 -(10 + 8))) then v6.HumanoidRootPart.CFrame=v21.CFrame + Vector3.new(0 -0 ,447 -(416 + 26) ,0) ;task.wait(180.4 -(67 + 113) );break;end end end end end v17=1;end end end end);end break;end end end);local v8=v1:NewSection("YT: Lion Mask");v8:CreateButton("YouTube Channel Link",function() local v13=0 + 0 ;local v14;while true do if ((2 -1)==v13) then game:GetService("StarterGui"):SetCore("SendNotification",{Title="Copied!",Text="YouTube Channel link copied to clipboard!",Duration=2 + 1 });break;end if (v13==(0 + 0)) then v14="https://youtube.com/@lion-masktv?si=gEjb64VNs49Gouhu";setclipboard(v14);v13=3 -2 ;end end end);
